#!/bin/sh /etc/rc.common

START=99
STOP=10

enable=$(uci get unblockmusic.@unblockmusic[0].enabled)
TYPE=$(uci get unblockmusic.@unblockmusic[0].musicapptype)
PORT=$(uci get unblockmusic.@unblockmusic[0].port)
IPSET=$(uci get unblockmusic.@unblockmusic[0].enable_ipset)
MUSIC_IP=$(ping music.163.com -c 1 | sed '1{s/[^(]*(//;s/).*//;q}')
ROUTE_IP=$(uci get network.lan.ipaddr)

set_firewall(){
	echo -e "ipset=/.music.163.com/music" >> /etc/dnsmasq.conf
	/etc/init.d/dnsmasq restart >/dev/null 2>&1

	mkdir -p /var/etc
	cat > "/var/etc/unblockmusic.include" <<-EOF
if ! ipset list music >/dev/null; then ipset create music hash:ip; fi
iptables -t nat -N cloud_music
iptables -t nat -A cloud_music -i br-lan -p tcp --dport 80 -j DNAT --to $ROUTE_IP:$PORT
iptables -t nat -A prerouting_rule -i br-lan -p tcp -m set --match-set music dst -j cloud_music
	EOF
	/etc/init.d/firewall restart >/dev/null 2>&1
}

reset_firewall(){
	echo "" > /var/etc/unblockmusic.include
	/etc/init.d/firewall restart >/dev/null 2>&1
	sed -i '/ipset=\/.music.163.com\/music/d' /etc/dnsmasq.conf
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

start()
{
	stop
	
	[ $enable -eq "0" ] && exit 0
	
	if [ $TYPE = "default" ]; then
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -f $MUSIC_IP >/tmp/unblockmusic.log 2>&1 &
	else
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT -f $MUSIC_IP -o $TYPE >/tmp/unblockmusic.log 2>&1 &
	fi
	
	[ $IPSET -ne "0" ] && set_firewall
	
	/usr/share/UnblockNeteaseMusic/logcheck.sh >/dev/null 2>&1 &
}

stop()
{
	kill -9 $(ps | grep monitor | grep -v grep | awk '{print $1}') >/dev/null 2>&1
	kill -9 $(ps | grep app.js | grep -v grep | awk '{print $1}') >/dev/null 2>&1
	kill -9 $(ps | grep logcheck.sh | grep -v grep | awk '{print $1}') >/dev/null 2>&1
	rm -f /tmp/unblockmusic.log

	reset_firewall
}



