#!/bin/sh /etc/rc.common

START=99
STOP=10

enable=$(uci get unblockmusic.@unblockmusic[0].enabled)
TYPE=$(uci get unblockmusic.@unblockmusic[0].musicapptype)
PORT=$(uci get unblockmusic.@unblockmusic[0].port)
HPORT=$(uci get unblockmusic.@unblockmusic[0].hport)
ROUTE_IP=$(uci get network.lan.ipaddr)

ipt_n="iptables -t nat"

add_rule()
{
  ipset -! -N music hash:ip
	$ipt_n -N cloud_music
	$ipt_n -A cloud_music -p tcp --dport 80 -j REDIRECT --to-ports 5200
	$ipt_n -A cloud_music -p tcp --dport 443 -j REDIRECT --to-ports 5201
	$ipt_n -I PREROUTING -p tcp -m set --match-set music dst -j cloud_music
	wget http://httpdns.n.netease.com/httpdns/v2/d?domain=p2.music.126.net,interface.music.163.com,interface3.music.163.com,clientlog.music.163.com,apm.music.163.com,apm3.music.163.com,p1.music.126.net,clientlog3.music.163.com -O- | grep -Eo '[0-9]+?\.[0-9]+?\.[0-9]+?\.[0-9]+?' | sort | uniq | awk '{print "ipset add music "$1}' > /tmp/musicip.txt
	sh /tmp/musicip.txt
}

del_rule(){
	$ipt_n -D PREROUTING -p tcp -m set --match-set music dst -j cloud_music 2>/dev/null
	$ipt_n -F cloud_music  2>/dev/null
	$ipt_n -X cloud_music  2>/dev/null
	
	rm -f /tmp/dnsmasq.d/dnsmasq-163.conf
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
}

set_firewall(){
	rm -f /tmp/dnsmasq.d/dnsmasq-163.conf
	mkdir -p /tmp/dnsmasq.d
	echo "dhcp-option=252,http://$ROUTE_IP:$PORT/proxy.pac" > /tmp/dnsmasq.d/dnsmasq-163.conf
	echo "ipset=/music.163.com/music" >> /tmp/dnsmasq.d/dnsmasq-163.conf
	echo "ipset=/interface.music.163.com/music" >> /tmp/dnsmasq.d/dnsmasq-163.conf
	/etc/init.d/dnsmasq restart >/dev/null 2>&1
	
	add_rule
	
	mkdir -p /var/etc
	cat > "/var/etc/unblockmusic.include" <<-EOF
/etc/init.d/unblockmusic restart
	EOF
}

start()
{
	stop
	
	[ $enable -eq "0" ] && exit 0
	
	if [ $TYPE = "default" ]; then
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT:$HPORT >/tmp/unblockmusic.log 2>&1 &
	else
			node /usr/share/UnblockNeteaseMusic/app.js -p $PORT:$HPORT -o $TYPE >/tmp/unblockmusic.log 2>&1 &
	fi
	
	set_firewall
	
	/usr/share/UnblockNeteaseMusic/logcheck.sh >/dev/null 2>&1 &
}

stop()
{
	kill -9 $(ps | grep app.js | grep -v grep | awk '{print $1}') >/dev/null 2>&1
	kill -9 $(ps | grep logcheck.sh | grep -v grep | awk '{print $1}') >/dev/null 2>&1
	rm -f /tmp/unblockmusic.log
	rm -f /tmp/music.log
	del_rule
}



